language: go

go:
  - "1.10"
  - "1.11"
  - "1.12"
  - "1.13"
  - "1.x"
  - master

install:
  - go get -d ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./... 

after_success:
  - bash <(curl -s https://codecov.io/bash)